# Generated by Django 5.0 on 2023-12-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('hero_name', models.CharField(max_length=100)),
                ('heroin_name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('budget', models.PositiveBigIntegerField()),
            ],
        ),
    ]
